title: Adegbola Gbolahan # your name (or website title) here
logo: "/images/gbola.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Adegbola Gbolahan is a Software Developer who has about five (5) years of experience in Android App Development.
  He is a graduate of the University of Ibadan, Ibadan and Nigerian Law School, Abuja.
  Having a law background, Adegbola has developed several mobile applications to aid legal education in Nigeria.
  Among them are - High Court of Lagos (Civil Procedure) Rules 2019 App and the Rules of Professional Conduct for Legal Practitioners in Nigeria 2007 App.
  He has also developed an Android App for the newly enacted Companies and Allied Matters Act (CAMA) 2020. All the above mentioned together with others have been published on Google Play Store.
  <br><br>
  Also, Adegbola has a vast knowledge of website development. In the past few years, he has developed online platforms (websites) for educational groups and NGOS.
  Among them are - VantageNetworkAfrica, LegalPages, Pipe Group and LSS UI.
  He was a member of the Developer Student Club while in the University, and now a member of Google Developers Group Ibadan - a voluntary group for developers who use google technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/gbolissimo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
